### ISSUE TITLE
TODO: Come up with idea for project.

### ISSUE THREAD

**Issue by ConorOHaleck** [ofHillsAndLakes/Project-Juliet-Omicron#1]

**Comment by majestiff** [comment]
Sorry, just learning how to work this. What is the hardest part? Is there a tag indicating this part?

**Comment by majestiff** [comment]
Ha. figured out what you meant by this. I guess we're still waiting for Robert to upload his codes...

**Comment by Coolcoderguy** [comment]
hey guys im new to this website. So where should I post the source code for all the classes? is there like a private message thing or should I just post it here?

**Comment by majestiff** [comment]
If you go on the main page of this project, there is a ' + ' next to the project name... above the small window listing files.

**Comment by Coolcoderguy** [comment]
ok cool I will do that now.

**Comment by Coolcoderguy** [comment]
all files have been posted

**Comment by majestiff** [comment]
Sweet! Thanks David!

**Comment by Coolcoderguy** [comment]
No problem. haha sorry I didn't mean to do all that work its just that I might be busy later on so I wanted to contribute as much as I could beforehand. 

I guess all we need to do is just implement graphics (to make our project look awesome!)

and just to debug a little so that the player or casino cant win if they go over 21 points in the game

**Comment by majestiff** [comment]
Okay.. so I guess there are a few things we need to do then. I have to look at your codes to familiarize myself with it, but I'm assuming that adding graphics (cards and what not) would require Joption pane? If i'm wrong please point it out! But if I am, we can began by converting the code into JOption... I'm trying to figure out how to bring over files from this to Eclipse right now... I don't even know how you can run the codes in here so yeah.. Anyways, we also need the pictures of cards... as well as adding on the method to allow player to use Ace as either one or eleven. So I guess that's three things we can do right now. Since you worked so hard and totally killed the skeletal work of our project, you can sit this out for now. :)

**Comment by Coolcoderguy** [comment]
its ok ill be glad to help when I can im trying to come up with a way to make graphics for the cards

**Comment by RobertBohlman** [comment]
Okay, I FINALLY was able to get a computer in front of me (busy day). I quickly skimmed over what you uploaded, but I was wondering, is there already a betting system implemented? Because if not, that's another possible task that I think is feasible.
