### ISSUE TITLE
I don't know

### ISSUE THREAD

**Issue by ghost** [ofHillsAndLakes/Project-Juliet-Omicron#12]

**Comment by majestiff** [comment]
I'm going to write a gui program for a hi-low game. Given that it has very basic rules in comparison to the blackjack, I think I can do this one.

**Comment by majestiff** [comment]
All right. Had a five hour sleep and thought about it.. I want to trash this project. I refuse to get caught and get marked for cheating when I had nothing to do with it. With that said, I want to write a new project. If you guys are against I, I will have to ask Straayer if I can get teamed up with someone else or do this solo. If I get asked why, I will tell him why. Not being a tattle tell, but I'm not allowing this bullshit to ruin my academic history.

**Comment by RobertBohlman** [comment]
Alright slow down there. Nothing's going up in flames. (For the record, five hours of sleep probably didn't help but I digress). If you ask me, the stuff we added/are working on will be more than enough to separate it. Besides, we can always change it more. At the end of the day, every program is going to have similarities with another, its inevitable. I did in fact see some differences in David's program versus the one you linked me (for the sake of tranparency, since I don't think anyone else knows what you're talking about: https://www.youtube.com/watch?v=buGFs1aQgaY&feature=youtu.be). I think we just all need to discuss this. Does everyone here have skype or something so the four of us can talk? Also David, if you did copy the program (if), please just be honest. We need to talk about this like adults, not jump to conclusions.

**Comment by RobertBohlman** [comment]
Also I'll just say now that I don't think its quite fair to the rest of us to trash the program, since we have spent time and effort on it. (Hell, you just mentioned you were up until 5 in the morning).

**Comment by majestiff** [comment]
Programs to this degree should not share such similarities to one that has already been written. And this isn't me jumping to a conclusion, this is a fact and it's evident even in the subnotes of the original and this one that was written. I'm just annoyed that he took credit for such a huge chunk of work (which left us --Conor and I-- with nothing to contribute into this project). I'm going to send Professor Straayer an email regarding this and will await further instructions from him.

**Comment by majestiff** [comment]
And of course it isn't fair that we start from scratch. But it also isn't fair that I get marked for cheating when I had no part (or wasn't given the chance to partake) in the original writing of this program;

**Comment by RobertBohlman** [comment]
Again, I think we all need to talk about this. Can you please hold off before emailing someone?

**Comment by RobertBohlman** [comment]
We need to hear David's side of the story, and Conor has been a bit quiet as well.

**Comment by Coolcoderguy** [comment]
whats going on here?

**Comment by RobertBohlman** [comment]
There are suspicions that the code you wrote was copied from a YouTube video. The link is above? Can you tell me this is true? Be honest please.

**Comment by Coolcoderguy** [comment]
i did not purposefully copy it, i used it as a reference and was going to alter it after we got the graphics into it before the submission, the graphics would not affect the code.

**Comment by RobertBohlman** [comment]
Okay, that's what I thought happened. Tiffany has already said a bunch of things to Straayer, and I contacted him and asked for a time we can meet up and discuss things. Hopefully you can help me explain this is a misunderstanding. Also, I'm sorry for all of this, I tried to keep a lid on it but it escalated beyond my control.

**Comment by Coolcoderguy** [comment]
it is! im not that stupid to do that lol. I would never do that, i just needed a reference. He even told us in class that we could use the internet for ideas, i was never going to leave it like this, i was going to modify it after we got the graphics done lol, it is a misunderstanding completely

**Comment by RobertBohlman** [comment]
Okay, we just need to explain that to Straayer next week. Again, I'm really sorry, I would have preferred to wait to say anything to anyone until we head from you.

**Comment by Coolcoderguy** [comment]
wait so what was exactly said?? i need to know lol

**Comment by RobertBohlman** [comment]
What do you mean, what Tiffany said or what I said?

**Comment by Coolcoderguy** [comment]
both please. i am not angry i just need to know, could you please be honest and tell me everything that was said by everyone?

**Comment by RobertBohlman** [comment]
Of course. As far as I know, Tiffany told Straayer that you plagiarized. I didn't think so and didn't want to say that unless we were sure. She then requested to be able to have her and Conor split from the group. Straayer agreed, though I don't think Conor even knows whats going on (he hasn't said anything) I then sent Straayer the following message.

**Comment by RobertBohlman** [comment]
"Hello, I'm apart of the team #4 that you were contacted by in regards to a potentially copied program. Here's the deal. Yirang contacted me and told me there was reason to suspect that the main bulk of our blackjack program for the final project, (written by David) was actually copied from a YouTube tutorial. She told me that you allowed her to leave the group, and I've tried to contact David in order to find out if the program is plagiarized. I can't get him to respond to me. I've already spent about 5 hours writing out a betting system for the game, (which I didn't know was copied) and I'll attach the files here to prove it. Can we meet up next week so we can discuss what's going to happen from here, and what direction should be taken? I don't want my work to go to waste, but I also don't want to be involved with plagiarism".

**Comment by RobertBohlman** [comment]
He agreed to us meeting up but we have yet to set a day and time, I think you should send him a message in canvas and explain a bit of your side before we meet up.

**Comment by Coolcoderguy** [comment]
i agree with you completely, i can start a new project today without even looking at the internet.

just need someone to be on my team. so i can write a new program within a week without even looking at the internet

**Comment by RobertBohlman** [comment]
Here's what I think we should do: I think you need to explain things to Sraayer and ask if its okay if you can rewrite the existing program to make it our own. If he agrees, then great, otherwise we need to pursue some other option. I think all four of us need to talk in person with him next week though.

**Comment by RobertBohlman** [comment]
Regardless of what he says on canvas, we should still meet.

**Comment by Coolcoderguy** [comment]
ok i agree. we should meet Wednesday after class since theres no class Monday and ill explain everything

**Comment by RobertBohlman** [comment]
Okay, send that to Straayer in canvas, tell him you talked with me, and explain a little of what happened.

**Comment by RobertBohlman** [comment]
Sound good?

**Comment by Coolcoderguy** [comment]
heres exactly what im going to say to Straayer : " yes i did use code from that youtube video, however, i had no intent of using that actual code. I was interested in seeing how a black jack program would actually look like when created. I was going to modify everything and make it my own work. This issue has been a misunderstanding, as there are millions of projects out there on the internet that people get ideas from. Therefore, i was not going to use the code created by the youtube video, i was going to modify it completely, i just needed a starting place to see how a code for such a program would look like."

**Comment by RobertBohlman** [comment]
Perfect, make sure to ask if we can meet after class Wednesday.

**Comment by Coolcoderguy** [comment]
ok thanks. if anything, i can create a new project. the only reason i needed that reference is because that project was going to be complex with many classes

**Comment by RobertBohlman** [comment]
I don't think we need to, and I gave reasons in my other posts, but I'm glad you are cooperating with me here, I think we can sort this out fine.

**Comment by Coolcoderguy** [comment]
heres what i wrote

**Comment by Coolcoderguy** [comment]
Dear Professor Straayer,

It has come to my attention that two of my group members have contacted you in regards to the final project. My side of the story is
that i never intended to use the code i have put into the skeleton of the project. I simply needed to see how such a project would
be created with all the methods used, since this project would not be simple. Again, this has been a misunderstanding, as I was
never going to use the code from the video. Looking from my team member's perspecitves, I understand why they contacted you as I
was unable respond to them for a couple days due not having internet access. I assure you that the final project created (with or 
without my team) will contain original work. Once again, I just needed to reference what a project like this was going to look like,
since it is not a simple project to create.

Sincerely,

David Zaks

**Comment by RobertBohlman** [comment]
Make sure to tell him you want to meet after class Wednesday with the rest of the group.

**Comment by RobertBohlman** [comment]
I'll try and get as many of us there as possible.

**Comment by Coolcoderguy** [comment]
ok. is the email fine?

**Comment by RobertBohlman** [comment]
Yes t looks good. Thanks again for your help, and I'm so sorry about all of this.

**Comment by Coolcoderguy** [comment]
me too, i should have told you guys, but in the end i was going to make it my own anyways as it was not going to affect the graphics

**Comment by RobertBohlman** [comment]
Its okay, what's important is that we have a chance to fix this.

**Comment by Coolcoderguy** [comment]
yea it was just an idea i needed, never ever was i going to submit that lol

**Comment by majestiff** [comment]
Just got around to reading everything. Once again, I mentioned no names but I'm glad that this has been clarified. I should have waited to hear your story but I was overwhelmed by everything when I had realized we couldn't use the program (this, when I thought you had intended for us to use this). If after discussing this matter with Straayer changes his current approval on me doing this final project solo, I guess I would have no choice. But at this moment I'm not a part of this group. But really, good luck guys and have fun. If the program that you rewrite is just as good as this current one, I look forward to seeing your presentation.

**Comment by Coolcoderguy** [comment]
i understand your perspective. At least we have it clarified.

**Comment by Coolcoderguy** [comment]
i also sent an email to him Tiffany, you can read if you would like it has been posted on this page just scroll up a bit, so im being completely open and honest :)

**Comment by majestiff** [comment]
Professor Straayer, it has come to my attention that the structure of our final project that one of my group member wrote is a copy from a tutorial found on YouTube. I have expressed my feeling of disconcert and have suggested that we scrap this project to start new. Given that so much time has been invested in this project, I can understand why my request was refused, but I have decided I want no part in it. It has been suggested that we restructure this entire program but given the fact that it wasn't our original programming puts me at unease. I am here to present this as my case in seek of your approval to allow me to work alone for our final project, or by allowing me to take one member from the group as my partner if he agrees to. Please advise, I look forward to hearing from you soon.

Like I said, no names.

**Comment by Coolcoderguy** [comment]
ok sounds good. Thanks for being honest with me.

**Comment by RobertBohlman** [comment]
Okay, so I confirmed with Straayer that we would talk to him after class tomorrow and clear everything up. The more of that can be there, the better.

**Comment by Coolcoderguy** [comment]
ok what did he say?

**Comment by RobertBohlman** [comment]
Just that he was free to discuss this with all of us so we can clear things up?

**Comment by ofHillsAndLakes** [comment]
Crap. I'm bad at keeping in touch, it's official. I was going to skip class today, finish up my code alterations to show you guys, and catch the lecture online. I logged into Github for the first time in a few days, and, well, guess I can forget pulling that code. So class is already starting at the time I'm typing this, but if any of you log in to Github during lecture, I can't be there for today but all is most certainly not lost. Let me know what Straayer says, and let me know what we're doing moving forward. If needs be, I can make a whole new blackjack program in a day or so, no need for drastic measures.

**Comment by RobertBohlman** [comment]
Sitting in class, David and I are about to go see if he will let us just restructure the code. We have backup ideas in case he doesn't too. Don't worry, we have everything under control.

**Comment by ofHillsAndLakes** [comment]
Cool. I'm honestly glad I can scrap what I was working on and start something new, whether that's a restructure of the existing code or something else entirely.

**Comment by RobertBohlman** [comment]
Okay, I'll be sure to tell you what Straayer says but do you already have a grasp on what has happened up to this point?

**Comment by ofHillsAndLakes** [comment]
I feel that I do, everything is timestamped, which helps.

**Comment by RobertBohlman** [comment]
Okay.

**Comment by RobertBohlman** [comment]
Alright I made a new issue, I suggest you all look at that.
