### ISSUE TITLE
Ace (one or eleven?)

### ISSUE THREAD

**Issue by ghost** [ofHillsAndLakes/Project-Juliet-Omicron#4]

**Comment by Coolcoderguy** [comment]
hmmm we could do both like the actual game is played. if we want to theme this to like the actual actual real game that people play in casinos we could have the option of 1 or 11

but if we wanted to make the game themed for a beginner, or someone who isn't super familiar with the game we could just make ace 1

**Comment by RobertBohlman** [comment]
Crap, that was a mistake

**Comment by majestiff** [comment]
Lol it's okay, I'm still learning this too... But we'll see. Let's get to converting it to JOptionPane. I haven't even started working on the Method for this thing yet so if we decide to not do this, that's fine too.

**Comment by RobertBohlman** [comment]
Yeah I don't know the first thing about incorporating graphics into Java so I don't know if I will be much help here. I posted in the other page that we could also try working in a betting system, unless that's already in (I don't think I saw anything though).

**Comment by majestiff** [comment]
Robert I didn't see it either. You can totally work on that! :)

**Comment by RobertBohlman** [comment]
Alright sounds good.

**Comment by Coolcoderguy** [comment]
yea guys. if we don't know anything about the graphics, we could so just do that the player bets x amount of dollars or coins or whatever for each round. and then we could keep track of how many wins they have or losses and their money they won.

After each round we could just prompt the user to either enter Yes / No when the game asks "do you wish to play again"

if the player says "Yes" 
the program could say "Please enter your bet"
if the player says no, program could say : " See you next time, Goodbye"

we could also make it so the player can only bet within their earnings so if they have like 500 coins they cant bet 600. 

If the player loses all their money or coins or whatever we want them to earn, the program can say" you have no money left, goodbye"


These are just quick ideas that I came up with since honestly I don't know anything about graphics, I think they would just complicate things.

If implement those things at the top, im sure we will be golden haha

**Comment by Coolcoderguy** [comment]
We can just let the player keep playing if they have enough coins given that they don't lose all their money. So if the player keeps winning they can earn up to infinity amount of dollars. I guess that would just be a loop, so the player keeps playing if they have enough money.

Lastly, we could just make the currency in dollars or coins but not both haha since if make the player earn coins which then they can redeem for money that would be a lot of work, unless you guys are up for it.

**Comment by RobertBohlman** [comment]
Uh, I'm not sure. I think I'll try to just get the system to work with dollars first, then maybe add that in if there's time.

**Comment by Coolcoderguy** [comment]
yea Robert I don't think you have to do both just do dollars or cents or whatever you wish to use for the currency. I don't think you have to do dollars and coins because if you did both that would be a lot of work. 

If we did dollars and coins then we would have to make the player win coins that can be transferred to dollars ( i.e. 1000 coins is 1 dollar).

So I think that we should just stick to dollars, would make it simpler, but still really good

**Comment by RobertBohlman** [comment]
Actually now that I think about it, isn't it just a simple math equation to say "You have made x dollars?". Might be a good idea for polish, but yeah you're right, I'll prioritize on making a working betting system.

**Comment by Coolcoderguy** [comment]
yea sounds good. you know what? im going to see if I can add casino music to the program when it runs so a casino theme song can play while we run it

**Comment by Coolcoderguy** [comment]
if that's even possible

**Comment by RobertBohlman** [comment]
Lol that would be pretty cool.

**Comment by Coolcoderguy** [comment]
yea im gonna try to do that today, we could meet up tomorrow in class and talk about it

**Comment by Coolcoderguy** [comment]
YAY! i figured out how to do it. im adding relaxing casino music to our program haha

**Comment by majestiff** [comment]
Lol! Dude that's awesome!! I can't wait to see it run tomorrow!

**Comment by Coolcoderguy** [comment]
Hopefully it runs on the school computer, i hope it has some kind of audio player installed, not iTunes obviously but windows media player which it probably work with the music portion

**Comment by RobertBohlman** [comment]
I don't think the school computers have any speakers, so you might need to bring some sort of audio output to plug in.

**Comment by Coolcoderguy** [comment]
i have headphones lol

**Comment by RobertBohlman** [comment]
Hey man, don't go assuming. That stuff's expensive. I had to fork over seven whole dollars for a pair last week. Had to explain to my family they couldn't eat that month. Hearts were broken.

**Comment by RobertBohlman** [comment]
Also, I might just upload what I have so far, do I need to create some new thing to separate it from what you're using?

**Comment by RobertBohlman** [comment]
Or just dump it in with everything else?

**Comment by Coolcoderguy** [comment]
Im sorry i just meant that i will bring some headphones so you guys can listen to it. I can't get it to work atm it might be with the file, the code has no error tho. Robert, hmm if you want you could just take the codes i pasted into the project and put them in eclipse and run them with your program you created to see how it works:)

**Comment by RobertBohlman** [comment]
Okay first of all the headphone comment was a joke lol. I guess sarcasm isn't easy to convey over text (a lesson I should have internalized by now). Now as for the piece, I already have a bit of a tester class up already, so I was planning to upload that too. Basically, you just have to edit one piece of a line to see all the scenarios. I'd kinda rather wait for a bit to merge everything, since I think that will take a bit of time.

**Comment by Coolcoderguy** [comment]
oh haha Robert you got me there. Yea sarcasm over text is hard to understand haha. yea i agree, we could just meet up tomorrow and talk about it during class as a group

**Comment by RobertBohlman** [comment]
Okay, sounds good.

**Comment by Coolcoderguy** [comment]
i just need to make this music work!! XD

**Comment by RobertBohlman** [comment]
I'd offer some help. but I have no idea how that works. And I may have put off some work when I did this (i.e. studying and the assignment due in Straayer's class tomorrow). I think this is the first time I've procrastinated with more schoolwork.

**Comment by Coolcoderguy** [comment]
yea ill look something up. Did you guys finish thing due monday

**Comment by RobertBohlman** [comment]
Nope, but its tactical procrastination. I know how to do it, just need to actually write the code.

**Comment by Coolcoderguy** [comment]
oh haha gotcha. i have the same problem in other subjects lol
