### ISSUE TITLE
JOption?

### ISSUE THREAD

**Issue by ghost** [ofHillsAndLakes/Project-Juliet-Omicron#6]

**Comment by majestiff** [comment]
With that said, I can rewrite this entire program Method heavy (like super method heavy) using David's original codes as my template.

**Comment by Coolcoderguy** [comment]
hmm yea you could. Robert and I were thinking of setting up a betting system where the user can bet money.

I was gonna see if i could add casino music to the program when it runs if that's possible.
Do you guys like that idea?

**Comment by majestiff** [comment]
So I've been looking at different options. I guess Java Graphics... whatever that is (haha) CAN be opted out altogether. Instead, we can use GUI (Graphical User Interface). The basics to this is in our textbook in Chapter 6. I'm looking through it now and it seems that this builds on the things we have learned in class so far. So I guess we can opt out Java Graphics and go with this route, so that we can present the user a table and cards. I'm also looking through BlackJack codes that other users have wrote using GUI on this website, and it seems like it will be a lot of work. Given, we have three weeks... but I want to see what you guys have to say.

I guess we should also ask Professor Straayer what he's looking for in our final project and what his requirements are. In a way I feel like he's not expecting us to present a project to this scale of level, but you can't be too sure...

**Comment by Coolcoderguy** [comment]
yea i agree. I'm adding music to the project, like casino music, since it takes a code for it to run when you open the program. 


To make things simple, we can just use scanner unless you guys want to use joption pane, as long as its consistent throughout we would be fine. As far as the program itself, we don't even have to do the betting system if we don't want to, we could just debug and polish the program and im writing a music code for it

**Comment by majestiff** [comment]
Okay so I'm experimenting with GUI and guys, I think this is it. We're going to work with GUI. But let me learn it more before I commit to this......  The code below is from the book that I tried to see what it would be like. It seems pretty basic enough and I think if we can get the program to run in this style, it would be aweeeeesome. :)

import javax.swing.JFrame;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;

public class BlackJack {

		private static class HelloWorldDisplay extends JPanel {
			public void paintComponent(Graphics g) {
				super.paintComponent(g);
				g.drawString("HELLOOOO" , 20, 30);
			}
		}
		
		private static class ButtonHandler implements ActionListener {
			public void actionPerformed(ActionEvent e) {
				
			}
		}
		public static void main(String[] args) {	
		
		HelloWorldDisplay displayPanel = new HelloWorldDisplay();
		JButton okButton = new JButton("OK");
		ButtonHandler listener =  new ButtonHandler();
		okButton.addActionListener(listener);
		
		JPanel content = new JPanel();
		content.setLayout(new BorderLayout());
		content.add(displayPanel, BorderLayout.CENTER);
		content.add(okButton, BorderLayout.SOUTH);

		JFrame window = new JFrame("YO");
		window.setContentPane(content);
		window.setSize(600, 700);
		window.setLocation(100,100);
		window.setVisible(true);
	}
}

**Comment by ofHillsAndLakes** [comment]
Swing is good. We can use Swing if we want to. If we have the time and effort though, we should use JavaFX: http://docs.oracle.com/javase/8/javafx/get-started-tutorial/jfx-overview.htm#JFXST784

**Comment by Coolcoderguy** [comment]
on Monday, we should quickly meet up like we always do. We could quickly do the powerpoint for the project like the week before its due. About the project, i like the gui idea! i think it would look so awesome. I feel like we should get extra credit lol. From last quarter i heard people got a lot of extra credit just by creating a program that would just shuffle numbers and add them up, so we better get appreciated hahahaha

**Comment by RobertBohlman** [comment]
Sounds good to me, David if you could upload the music code I'd like to mess with adding some sound effects as well (I made an issue about it). Also Connor, I saw the update you put in the readme. Do you still want me to handle integrating the betting into the main code?

**Comment by Coolcoderguy** [comment]
can someone call me please at 253 324 0342 right now  I don't know whats going on????
