### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ghost** [ofHillsAndLakes/Project-Juliet-Omicron#9]

**Comment by majestiff** [comment]
Conor, let me upload my codes first and then you can put the finishing touches on it --since you're very good at the miniscule detail of things.

**Comment by majestiff** [comment]
And I think Robert and David can sit out for a while. Conor and I haven't done much to contribute to this project yet, so we can take it from here. We'll definitely ask for assistance as needed, but please allow us to do our part too. Thank you Robert and David!!!! :D

**Comment by majestiff** [comment]
All right.... I have the basic layout (table, bg color, hit/stand/sound on and off buttons) and added an image file to link to the game instead of the text. The program is still in David's text based mode but it is now linked to the images (it prints the location of said images since it is still in text based form). I've tweaked things to the main program a little so that it will run based on the things I've linked it to... Now I have to integrate the program so that it runs through GUI. I'm going to do that next and upload that to show you guys what I have so far but I warn you, it will be a rough draft and not yet a complete version.

**Comment by Coolcoderguy** [comment]
That sounds awesome! Can't wait to see it! Oh and with the music it will be so cool. This is kind of random, but we as Im counting, it looks like we will have like 8 classes all together, with the game itself plus the music plus the betting system. We should totally just quickly meet up on Wednesday and just briefly look over everything and once all the hard stuff is done just make little tweaks to make it look good. I honestly can't wait to see the final product!
